apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-storage
  namespace: foundry-idp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath  # Use Docker Desktop default storage class

